name: Lint (Python) ğŸ§¹

on:
  push:
    branches: [main,feature/ci-github-actions]
  pull_request:
    branches: [main]

jobs:
  lint:
    strategy:
      matrix:
        OS: [ubuntu-latest]
        python: [3.12.3]

    name: Lint with pylint ğŸ§ª, blue ğŸ”µ, and isort ğŸ“š
    runs-on: ${{ matrix.OS }}

    steps:
      - name: Checkout code ğŸ›’
        uses: actions/checkout@v2
      
      - name: Set up Python ğŸ version ${{ matrix.python }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}

      - name: Update pip ğŸ”‚
        run: python -m pip install --upgrade pip

      - name: Install dependencies ğŸ“¦
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run pylint ğŸ§ª
        continue-on-error: true
        run: |
          find . -type f -name "*.py" | xargs pylint

      - name: Run blue ğŸ”µ
        continue-on-error: true
        run: |
          blue --check .

      - name: Run isort ğŸ“š
        continue-on-error: true
        run: |
          isort --profile=black --check-only .
