name: Lint (Python) ğŸ§¹

on:
  push:
    branches: [main,feature/ci-github-actions]
  pull_request:
    branches: [main]

jobs:
  lint:
    name: Lint with pylint ğŸ§ª, blue ğŸ”µ, and isort ğŸ“š
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code ğŸ›’
        uses: actions/checkout@v2
      
      - name: Set up Python ğŸ
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Update pip ğŸ”‚
        run: python -m pip install --upgrade pip

      - name: Install dependencies ğŸ“¦
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run pylint ğŸ§ª
        continue-on-error: true
        run: |
          pylint .

      - name: Run blue ğŸ”µ
        continue-on-error: true
        run: |
          blue --check .

      - name: Run isort ğŸ“š
        continue-on-error: true
        run: |
          isort --profile=black --check-only .
